- name: VBR Module Tests
  hosts: veeam
  gather_facts: no
  tasks:
  - name: Get Veeam Facts
    veeam_connection_facts:
    register: my_facts
  - name: Debug Veeam Facts
    debug:
        var: my_facts
  - name: Add credential
    veeam_credential:
        state: present
        type: windows
        username: Administrator
        password: ChangeMe
        description: dummy description